#!/usr/bin/env python3
"""Phase 2 pretraining script for Nano-Alpha 130M Llama.

Trains from scratch using the frozen phase1 dataset and saves intermediate
checkpoints every N steps for later logit-based evaluation.
"""

from __future__ import annotations

import argparse
import inspect
import json
import os
from pathlib import Path
from typing import Dict

from datasets import Dataset, load_dataset
from transformers import (
    DataCollatorForLanguageModeling,
    LlamaConfig,
    LlamaForCausalLM,
    PreTrainedTokenizerFast,
    Trainer,
    TrainingArguments,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train Nano-Alpha 130M Llama from scratch")
    parser.add_argument(
        "--train-file",
        type=Path,
        default=Path("data/processed/phase1_v2_de_eval/train_corpus.jsonl"),
        help="Path to train corpus JSONL",
    )
    parser.add_argument(
        "--val-file",
        type=Path,
        default=Path("data/processed/phase1_v2_de_eval/val_corpus.jsonl"),
        help="Path to val corpus JSONL",
    )
    parser.add_argument(
        "--tokenizer-file",
        type=Path,
        default=Path("artifacts/tokenizer/nano_alpha_bpe.tokenizer.json"),
        help="Path to tokenizer JSON generated by train_tokenizer.py",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("checkpoints/nano-alpha-130m"),
        help="Directory for checkpoints and trainer outputs",
    )
    parser.add_argument("--max-steps", type=int, default=5000, help="Total optimization steps")
    parser.add_argument("--save-steps", type=int, default=500, help="Checkpoint save interval")
    parser.add_argument(
        "--save-total-limit",
        type=int,
        default=0,
        help="Maximum number of checkpoints to keep on disk (0 means keep all)",
    )
    parser.add_argument("--eval-steps", type=int, default=500, help="Evaluation interval")
    parser.add_argument("--logging-steps", type=int, default=20, help="Logging interval")
    parser.add_argument("--seq-length", type=int, default=1024, help="Sequence length for CLM")
    parser.add_argument("--train-batch-size", type=int, default=2, help="Per-device train batch size")
    parser.add_argument("--eval-batch-size", type=int, default=2, help="Per-device eval batch size")
    parser.add_argument("--grad-accum-steps", type=int, default=16, help="Gradient accumulation steps")
    parser.add_argument("--learning-rate", type=float, default=3e-4, help="Learning rate")
    parser.add_argument("--weight-decay", type=float, default=0.1, help="Weight decay")
    parser.add_argument("--warmup-ratio", type=float, default=0.03, help="Warmup ratio")
    parser.add_argument("--num-proc", type=int, default=4, help="Dataset map workers")
    parser.add_argument("--max-train-samples", type=int, default=0, help="0 means all train rows")
    parser.add_argument("--max-val-samples", type=int, default=0, help="0 means all val rows")
    parser.add_argument("--bf16", action="store_true", help="Enable bf16 mixed precision")
    parser.add_argument("--fp16", action="store_true", help="Enable fp16 mixed precision")
    parser.add_argument("--seed", type=int, default=42, help="Random seed")
    parser.add_argument(
        "--report-to",
        type=str,
        default="mlflow,wandb",
        help="Comma-separated reporting backends (e.g. 'mlflow', 'wandb', 'mlflow,wandb', or 'none')",
    )
    parser.add_argument(
        "--mlflow-tracking-uri",
        type=str,
        default=None,
        help="Optional MLflow tracking URI override (e.g. file:/path/to/mlruns or https://mlflow.server)",
    )
    parser.add_argument(
        "--mlflow-experiment-name",
        type=str,
        default=None,
        help="Optional MLflow experiment name override",
    )
    parser.add_argument(
        "--resume-from-checkpoint",
        type=Path,
        default=None,
        help="Path to checkpoint to resume from (e.g. checkpoints/nano-alpha-130m-v100/checkpoint-1000)",
    )
    parser.add_argument(
        "--resume-id",
        type=str,
        default=None,
        help="W&B run ID to resume (e.g. from trainer_state.json). Resumes in same run if provided.",
    )
    args = parser.parse_args()
    if args.bf16 and args.fp16:
        raise ValueError("Choose only one of --bf16 or --fp16")
    return args


def load_text_dataset(path: Path, max_rows: int) -> Dataset:
    ds = load_dataset("json", data_files=str(path), split="train")
    if max_rows > 0:
        ds = ds.select(range(min(max_rows, len(ds))))
    return ds


def tokenize_and_chunk(ds: Dataset, tokenizer: PreTrainedTokenizerFast, seq_length: int, num_proc: int) -> Dataset:
    if "text" not in ds.column_names:
        raise ValueError("Expected 'text' column in dataset")

    def tokenize_fn(batch: Dict[str, list]) -> Dict[str, list]:
        return tokenizer(batch["text"], add_special_tokens=True, truncation=False)

    tokenized = ds.map(
        tokenize_fn,
        batched=True,
        num_proc=num_proc,
        remove_columns=ds.column_names,
        desc="Tokenizing",
    )

    def group_texts(examples: Dict[str, list]) -> Dict[str, list]:
        concatenated = {k: sum(examples[k], []) for k in examples.keys()}
        total_length = len(concatenated["input_ids"])
        total_length = (total_length // seq_length) * seq_length
        if total_length == 0:
            return {"input_ids": [], "attention_mask": [], "labels": []}

        result = {
            k: [t[i : i + seq_length] for i in range(0, total_length, seq_length)]
            for k, t in concatenated.items()
        }
        result["labels"] = [chunk[:] for chunk in result["input_ids"]]
        return result

    return tokenized.map(
        group_texts,
        batched=True,
        num_proc=num_proc,
        desc="Chunking",
    )


def build_model(vocab_size: int) -> LlamaForCausalLM:
    config = LlamaConfig(
        vocab_size=vocab_size,
        hidden_size=768,
        intermediate_size=2048,
        num_hidden_layers=12,
        num_attention_heads=12,
        max_position_embeddings=1024,
        pad_token_id=0,
        bos_token_id=1,
        eos_token_id=2,
    )
    return LlamaForCausalLM(config)


def main() -> None:
    args = parse_args()

    for required in (args.train_file, args.val_file, args.tokenizer_file):
        if not required.exists():
            raise FileNotFoundError(f"Required file not found: {required}")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    tokenizer = PreTrainedTokenizerFast(tokenizer_file=str(args.tokenizer_file))
    tokenizer.add_special_tokens(
        {
            "pad_token": "<pad>",
            "bos_token": "<s>",
            "eos_token": "</s>",
            "unk_token": "<unk>",
        }
    )
    # We chunk token streams manually to seq_length later, so disable tokenizer-side
    # max length warnings for long raw documents.
    tokenizer.model_max_length = int(1e12)

    print("Loading corpus...")
    raw_train_ds = load_text_dataset(args.train_file, args.max_train_samples)
    raw_val_ds = load_text_dataset(args.val_file, args.max_val_samples)

    print("Tokenizing and chunking train set...")
    train_ds = tokenize_and_chunk(raw_train_ds, tokenizer, args.seq_length, args.num_proc)
    print("Tokenizing and chunking val set...")
    eval_ds = tokenize_and_chunk(raw_val_ds, tokenizer, args.seq_length, args.num_proc)

    if len(train_ds) == 0 or len(eval_ds) == 0:
        raise ValueError("Tokenized train or eval dataset is empty; lower --seq-length or check inputs")

    model = build_model(vocab_size=tokenizer.vocab_size)
    model.resize_token_embeddings(tokenizer.vocab_size)

    # Parse reporting backends. Allows combinations like "mlflow,wandb".
    report_raw = [item.strip() for item in args.report_to.split(",") if item.strip()]
    if not report_raw or "none" in report_raw:
        report_to = []
    else:
        allowed = {"wandb", "mlflow"}
        unknown = [item for item in report_raw if item not in allowed]
        if unknown:
            raise ValueError(f"Unsupported report_to backend(s): {unknown}. Allowed: {sorted(allowed)}")
        # Keep order while removing duplicates.
        report_to = list(dict.fromkeys(report_raw))

    # Optional MLflow env wiring for local/remote servers.
    if args.mlflow_tracking_uri:
        os.environ["MLFLOW_TRACKING_URI"] = args.mlflow_tracking_uri
    if args.mlflow_experiment_name:
        os.environ["MLFLOW_EXPERIMENT_NAME"] = args.mlflow_experiment_name

    ta_kwargs = {
        "output_dir": str(args.output_dir),
        "max_steps": args.max_steps,
        "per_device_train_batch_size": args.train_batch_size,
        "per_device_eval_batch_size": args.eval_batch_size,
        "gradient_accumulation_steps": args.grad_accum_steps,
        "learning_rate": args.learning_rate,
        "weight_decay": args.weight_decay,
        "warmup_ratio": args.warmup_ratio,
        "logging_strategy": "steps",
        "logging_steps": args.logging_steps,
        "logging_first_step": True,
        "save_strategy": "steps",
        "save_steps": args.save_steps,
        "save_total_limit": None if args.save_total_limit == 0 else args.save_total_limit,
        "eval_steps": args.eval_steps,
        "bf16": args.bf16,
        "fp16": args.fp16,
        "lr_scheduler_type": "cosine",
        "report_to": report_to,
        "run_name": "nano-alpha-130m-phase2",
        "seed": args.seed,
        "data_seed": args.seed,
    }

    # Handle API differences across transformers versions on HPC.
    ta_params = inspect.signature(TrainingArguments.__init__).parameters
    if "overwrite_output_dir" in ta_params:
        ta_kwargs["overwrite_output_dir"] = True
    if "eval_strategy" in ta_params:
        ta_kwargs["eval_strategy"] = "steps"
    elif "evaluation_strategy" in ta_params:
        ta_kwargs["evaluation_strategy"] = "steps"

    training_args = TrainingArguments(**ta_kwargs)

    collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    trainer_kwargs = {
        "model": model,
        "args": training_args,
        "train_dataset": train_ds,
        "eval_dataset": eval_ds,
        "data_collator": collator,
    }

    trainer_params = inspect.signature(Trainer.__init__).parameters
    if "tokenizer" in trainer_params:
        trainer_kwargs["tokenizer"] = tokenizer
    elif "processing_class" in trainer_params:
        trainer_kwargs["processing_class"] = tokenizer

    trainer = Trainer(**trainer_kwargs)

    # Determine checkpoint to resume from
    resume_checkpoint = None
    if args.resume_from_checkpoint:
        resume_checkpoint = str(args.resume_from_checkpoint)
        print(f"Resuming from checkpoint: {resume_checkpoint}")
    
    # W&B run ID for continuation (resume in same run)
    if args.resume_id:
        os.environ["WANDB_RUN_ID"] = args.resume_id
        print(f"Continuing W&B run: {args.resume_id}")

    print("Starting training...")
    train_result = trainer.train(resume_from_checkpoint=resume_checkpoint)

    print("Saving final model...")
    trainer.save_model(str(args.output_dir / "final"))
    tokenizer.save_pretrained(str(args.output_dir / "final"))

    metrics = dict(train_result.metrics)
    metrics["train_samples"] = len(train_ds)
    metrics["eval_samples"] = len(eval_ds)

    metrics_path = args.output_dir / "train_metrics.json"
    metrics_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")

    print("Training complete.")
    print(f"Metrics: {metrics_path}")


if __name__ == "__main__":
    main()
